let g:vim_home = get(g:, 'vim_home', expand('~/.vim/'))


" junegunn/vim-plug
call plug#begin(g:vim_home.'/.plugged')

	" themes
	Plug 'gruvbox-community/gruvbox'
	Plug 'vim-airline/vim-airline-themes'

	" common
	Plug 'tpope/vim-vinegar'
	Plug 'vim-airline/vim-airline'

	" syntax extensions
	Plug 'sheerun/vim-polyglot'
	Plug 'leafgarland/typescript-vim'
	Plug 'pangloss/vim-javascript'
	Plug 'rhysd/vim-goyacc'

	" lsp
	Plug 'neovim/nvim-lspconfig'
	Plug 'simrat39/symbols-outline.nvim'

call plug#end()


" customizing
exec 'source' g:vim_home.'_vimrc.min'

" plugins configurations
let setup_files = split(globpath(g:vim_home, '*_setup.vim'), '\n')
for setup_file in setup_files
	exec 'source' setup_file
endfor
let setup_files = split(globpath(g:vim_home, '*_setup.lua'), '\n')
for setup_file in setup_files
	exec 'source' setup_file
endfor
