let g:vim_home = get(g:, 'vim_home', expand('~/.vim/'))


" junegunn/vim-plug
call plug#begin(g:vim_home.'/.plugged')

	" themes
	Plug 'joshdick/onedark.vim'

	" common
	Plug 'tpope/vim-vinegar', { 'tag': 'v1.*' }
	Plug 'vim-syntastic/syntastic', { 'tag': '3.*' }
	Plug 'vim-airline/vim-airline'
	if executable('ctags')
		Plug 'preservim/tagbar', { 'tag': 'v3.*' }
	endif
	"Plug 'neovim/nvim-lspconfig', { 'tag': 'v0.1.*'}

	" syntax extensions
	Plug 'sheerun/vim-polyglot'
	Plug 'rhysd/vim-goyacc'

	" golang
	if executable('go')
		Plug 'fatih/vim-go', { 'tag': 'v1.*' }
	endif
	" typescript
	if executable('tsc')
		Plug 'leafgarland/typescript-vim'
		Plug 'Quramy/tsuquyomi'
	endif
	" rust
	if executable('rustc')
		Plug 'rust-lang/rust.vim'
	endif

call plug#end()


" customizing
exec 'source' g:vim_home.'_vimrc.min'

" plugins configurations
let setup_files = split(globpath(g:vim_home, '*_setup.vim'), '\n')
for setup_file in setup_files
	exec 'source' setup_file
endfor
